name: triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

  repository_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-18.04
    steps:
    - run: |
        sudo apt-get update
        sudo apt-get install binfmt-support qemu-user-static
        git clone https://github.com/rockchip-linux/rk-rootfs-build
        cd rk-rootfs-build
        sudo dpkg -i ubuntu-build-service/packages/*
        sudo apt-get install -f
        RELEASE=buster TARGET=desktop ARCH=arm64 ./mk-base-debian.sh